# Site settings
baseurl = "https://graffiti.pestrickland.co.uk/"
languageCode = "en-gb"
title = "Graffiti Notebook"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "G-7KV1FFSL2L"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Graffiti Notebook"
    subtitle = "A simple record of the various graffiti and tagging I find."
    author = "P E Strickland"
    description = "Photographs and critiques of graffiti and tagging. Tongue-in-cheek."
    keywords = "Photography, Satire"

    # Body background color
    bodybgcolor = "#aab8c4"

    # Preview container button text
    buttontext = "Read more"

    # Footer text
    footertext = """Site built with [Hugo](http://gohugo.io). Powered by netlify.
    Theme by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/)
    and [Pavel Kanyshev](https://github.com/aerohub)"""

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
